(() => {
  try {
    console.log("hello");
  } catch (reason) {
    console.error(reason);
  }
})();
